---
driver:
  name: ec2
  security_group_ids: ["sg-69ce330d"]
  subnet_id: subnet-2f5f9f04
  region: us-east-1
  ssh_key: <%= ENV['AWS_SSH_KEY'] %>
  availability_zone: us-east-1e
  flavor_id: t2.medium
  image_id: ami-92dfa7fa
  iam_profile_name: TestKitchenRole
  associate_public_ip: false
  username: ubuntu
  user_data: "#!/bin/bash\napt-get update"
  ssh_timeout: 20
  ssh_retries: 5
platforms:
  - name: ubuntu-14.04
    driver:

provisioner:
  name: chef_zero
  require_chef_omnibus: 11.16.4

suites:
- name: default
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_mysql::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_mysql::default]
  attributes:
    chef_client:
      reload_config: false
    percona:
      encrypted_data_bag_secret_file: '/tmp/kitchen/encrypted_data_bag_secret'
      use_percona_repos: false
    optoro_mysql:
      backup_database_name: "inventory_production"
      backup_database_user: "optiturn"
      use_custom_repo: true

- name: zfs
  encrypted_data_bag_secret_key_path: "test/integration/encrypted_data_bag_secret"
  run_list:
    - recipe[optoro_mysql::test]
    - recipe[optoro_aptly::repos]
    - recipe[optoro_mysql::default]
  attributes:
    chef_client:
      reload_config: false
    percona:
      encrypted_data_bag_secret_file: '/tmp/kitchen/encrypted_data_bag_secret'
      use_percona_repos: false
      conf:
        mysqld:
          innodb-log-group-home-dir: '/mysql/innodb_logs'
          innodb_use_native_aio: '0'
          innodb_data_home_dir: '/mysql/innodb_data'
    optoro_mysql:
      backup_database_name: "inventory_production"
      backup_database_user: "optiturn"
      use_custom_repo: true
      use_zfs: true
