name 'optoro_mysql'
maintainer 'Optoro'
maintainer_email 'devops@optoro.com'
license 'MIT'
description 'This is a wrapper around the percona cookbook'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version '0.0.14'

supports 'ubuntu', '= 14.04'

provides 'backup'
provides 'default'
provides 'logrotate'
provides 'users'
provides 'zfs'

recipe 'default', 'Installs Percona MySQL'
recipe 'backup', 'Installs Backup scripts for MySQL'
recipe 'logrotate', 'Configures rotation of MySQL logs'
recipe 'users', 'Creates user accounts for MySQL'
recipe 'zfs', 'Creates ZFS device for MySQL data'

depends 'percona', '~> 0.16.0'
depends 'sysctl'
depends 'database', '~> 4.0.3'
depends 'apt'
depends 'openssl'
depends 'logrotate'
depends 'cron'
depends 'optoro_metrics'
